### ISSUE TITLE
Minnesota data and readme issue

### ISSUE THREAD

**Issue by Max-Hailperin** [MEDSL/2022-elections-official#1]
The readme speculates that the thousands of write-in rows in the Minnesota dataset that are identical except for vote counts are because distinct write-in candidates are getting their own rows, but all with the name field having WRITE-IN. This speculation is incorrect. The rows that are duplicates aside from vote count instead originate from a data problem, as described below. So this section of the read-me should be deleted and the data should be fixed.

Note that all the thousands of near-duplicate rows have the office of SOIL AND WATER SUPERVISOR. The problem is that the district field in the state's data set does not in fact record the district for soil and water supervisors. The only reliable way to get the correct district number is to strip it out of the full textual name of the office, for example "Soil and Water Supervisor District 3."

Once these district numbers are corrected, there will no longer be any duplicates; the WRITE-IN rows will all be showing the total number of write-ins for each office in each precinct.

**Comment by sbaltzmit** [comment]
Oh thanks, great catch! And thank you for the detailed report. Hopefully the change I just pushed fixed the issue. Closing for now but let me know if the issue remains.
