### ISSUE TITLE
LA state house races only contain candidate TANNER MAGEE

### ISSUE THREAD

**Issue by NickCrews** [MEDSL/2022-elections-official#11]
There are only 398 rows for `state_po=="LA"` and `office=="STATE HOUSE"` races, and in all of them the district column is null. Upon looking into it further, they are all for the candidate "TANNER MAGEE"

**Comment by sbaltzmit** [comment]
This turned out to be just an incorrect office name: State House elections in Louisiana take place on odd-numbered years. This candidate was actually a judicial candidate. I've uploaded a corrected dataset.

**Comment by NickCrews** [comment]
yay, thanks! That makes sense.
