### ISSUE TITLE
Include notebooks/scripts that parse the source data

### ISSUE THREAD

**Issue by NickCrews** [MEDSL/2022-elections-official#12]
In the readme you list the sources that you are finding the data from, and sometimes the cleaning steps you had to do. It would be ideal if you could also include the actual source code that you used to do this. This would have the benefits of
- be reproducible
- understand the details of the process. eg the written explanation of what you had to do with vermont is not totally clear to me. Actual code would be totally unambiguous.
- do the cleaning again/myself, in case the departments of state release updated/fixed/new data.
- audit the code to verify there aren't bugs in there that will throw off downstream analysis. For example, if you look at the data table in https://github.com/MEDSL/2022-elections-official/issues/7, 40% of VT STATE HOUSE districts are NULL. Why is that? I would like to be able to look upstream and track down the cause of this.

**Comment by sbaltzmit** [comment]
See https://github.com/MEDSL/replication-scripts. 2022 is in progress, so the code is not finalized, but we will upload them when they are.
