### ISSUE TITLE
MS 2022 general results still incorrect

### ISSUE THREAD

**Issue by grantschwab** [MEDSL/2022-elections-official#4]
Hello again! Just FYI: I took a look at the new file you uploaded, and it seems the incorrect results are still there. When I compare the precinct-level results in MEDSL's file against the state's county totals, I get the same discrepancies as before.

Best,
Grant @ RDH

**Comment by grantschwab** [comment]
Yup, looks good now. Thanks again!

**Comment by sbaltzmit** [comment]
Great, thank you!
