### ISSUE TITLE
Districts for US HOUSE in Alaska are NULL, should be STATEWIDE or AT-LARGE

### ISSUE THREAD

**Issue by NickCrews** [MEDSL/2022-elections-official#8]
AK only gets one rep to the US house of reps, so they have a single at-large district. But other states like ND are in this same situation, but they have this encoded as "AT-LARGE", which I think makes more sense. NULL implies to me "unknown"

**Comment by sbaltzmit** [comment]
Thanks. Please see my comment in #5 , https://github.com/MEDSL/2022-elections-official/issues/5#issuecomment-1977164412. This is also a question of cross-state standardization regarding how to represent non-district-based offices. Null is currently my intended countrywide standard. There is an argument that at-large offices are a different animal and should be represented by a value like `AT-LARGE`. I think that makes sense at least for state or federal legislatures, and we have done this in the past, but this is also difficult to standardize below the level of state legislatures or so, so I also have mixed feelings about exactly how to implement it for 2022. The intended timeline to finalize and impose these standards is April-May. I'll close this thread for now but I will leave the other comment open as a representation of the outstanding district standardization issue, and thanks again for bringing our attention to it.

**Comment by sbaltzmit** [comment]
and your comment is definitely a fair  point -- it should definitely be encoded the same way across states for the same office, especially for US HOUSE.
